name: royal_app
description: Isle Royal — AI Automatic Office Backend for Saint Mary Liberty Island
publish_to: 'none'
version: 2.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^1.2.0
  provider: ^6.1.0
  intl: ^0.20.2
  google_fonts: ^6.1.0
  flutter_animate: ^4.5.0
  shared_preferences: ^2.2.0
  models:
    path: ../shared/models
  flutter_gen: ^5.3.1
  bip39: ^1.0.6
  convert: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_gen_runner: ^5.3.1
  build_runner: ^2.4.0

flutter:
  uses-material-design: true
  generate: true
