[INFORMATION]
# AGPLv3 license requires that you make any source code modifications
# available to the end users of the server.
# LICENSE: https://github.com/simplex-chat/simplexmq/blob/stable/LICENSE
# Include correct source code URI in case the server source code is modified in any way.
# source_code = https://github.com/simplex-chat/simplexmq

# Declaring all below information is optional, any of these fields can be omitted.
# server_country = ISO-3166 2-letter code
# operator = entity (organization or person name)
# operator_country = ISO-3166 2-letter code
# website =
# admin_simplex = SimpleX address
# admin_email =
# complaints_simplex = SimpleX address
# complaints_email =
# hosting = entity (organization or person name)
# hosting_country = ISO-3166 2-letter code
# hosting_type = virtual

[STORE_LOG]
# The server uses STM memory for persistence,
# that will be lost on restart (e.g., as with redis).
# This option enables saving memory to append only log,
# and restoring it when the server is started.
# Log is compacted on start (deleted objects are removed).
enable = on

# File storage mode: `memory` or `database` (PostgreSQL).
store_files = memory

# Database connection settings for PostgreSQL database (`store_files = database`).
# db_connection = postgresql://xftp@/xftp_server_store
# db_schema = xftp_server
# db_pool_size = 10

# Write database changes to store log file
# db_store_log = off

# Expire files after the specified number of hours.
expire_files_hours = 48

log_stats = off

# Log interval for real-time Prometheus metrics
# prometheus_interval = 60

[AUTH]
# Set new_files option to off to completely prohibit uploading new files.
# This can be useful when you want to decommission the server, but still allow downloading the existing files.
new_files = on

# Use create_password option to enable basic auth to upload new files.
# The password should be used as part of server address in client configuration:
# xftp://fingerprint:password@host1,host2
# The password will not be shared with file recipients, you must share it only
# with the users who you want to allow uploading files to your server.
# create_password = password to upload files (any printable ASCII characters without whitespace, '@', ':' and '/')

# control_port_admin_password =
# control_port_user_password =

[TRANSPORT]
# host is only used to print server address on start
host = simplex-node.local
port = 443
log_tls_errors = off
# control_port = 5226

[FILES]
path = /srv/xftp
storage_quota = 20gb

[INACTIVE_CLIENTS]
# TTL and interval to check inactive clients
disconnect = off
# ttl = 21600
# check_interval = 3600

[WEB]
# Set path to generate static mini-site for server information
static_path = /var/opt/simplex-xftp/www

# Run an embedded HTTP server on this port.
# http = 8000

# TLS credentials for HTTPS web server on the same port as XFTP.
# cert = /etc/opt/simplex-xftp/web.crt
# key = /etc/opt/simplex-xftp/web.key
